<?php

/** @file
 * This file describe how to use hook function
 */

/**
 * Implement hook_cron();
 */
 function mymodule_cron() {
 \Drupal::messenger()->addMessage(t("Hello from my module cron hook"));
}

/**
 * Implement hook_form_alter()
 */

function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
 if($form_id == 'node_article_edit_form'){
    $form['action']['submit']['#value'] = t("save this awesome article!");
 }
}